server:
  port:
    8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

auth:
  jwt-expiration-ms: 1800000